inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  # Exclude overrides the whole definition so we need to copy it
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/**/*'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'
    # Additional exclude files by rubocop-rails_config
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'docs/**/*'
    - 'lib/tasks/*'
